
services:
  node-app:
   container_name: express-node-app-container
   image: menna12345/node-app  # name of repo in docker hub to push image 
   build: .
   ports:
    - "4000:4000"
   environment:
    PORT: 4000
   depends_on:
    - mongo 
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db   #mongo_db this volumn name i created it down to store data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nginx:
   image: nginx:stable-alpine
   ports:
    - "8080:80"
   volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - node-app


volumes:
   mongo_db: # name of volume


